// ============================================================
// Vellix Academy – Content Data
// ============================================================

export const courses = [
  {
    id: 1,
    slug: "full-stack-web-development",
    title: "Full-Stack Web Development",
    shortTitle: "Full-Stack Web Dev",
    description:
      "Build complete web applications with React, Node.js, REST APIs, databases & cloud deployment. Enterprise-grade from day one.",
    instructor: "Ahmed Muhsin",
    instructorSlug: "ahmed",
    instructorImg: "/images/instructors/ahmed.jpg",
    thumbnail: "/images/courses/web-dev.jpg",
    category: "software-engineering",
    categoryLabel: "Software Engineering",
    link: "/courses/full-stack-web-development",
    duration: "6 months",
    type: "Full-Time",
  },
  {
    id: 2,
    slug: "enterprise-java-spring-boot",
    title: "Enterprise Java & Spring Boot",
    shortTitle: "Enterprise Java",
    description:
      "Master enterprise Java with Spring Boot, Microservices, API design, and enterprise integration patterns used in Fortune 500 companies.",
    instructor: "Ruwaidha Hakeem",
    instructorSlug: "ruwaidha",
    instructorImg: "/images/instructors/ruwaidha.jpg",
    thumbnail: "/images/courses/java-enterprise.jpg",
    category: "software-engineering",
    categoryLabel: "Software Engineering",
    link: "/courses/enterprise-java-spring-boot",
    duration: "4 months",
    type: "Full-Time",
  },
  {
    id: 3,
    slug: "data-science-machine-learning",
    title: "Data Science & Machine Learning",
    shortTitle: "Data Science & AI",
    description:
      "Python, Pandas, NumPy, Scikit-Learn, TensorFlow & model deployment. Learn to build and ship production-grade AI pipelines.",
    instructor: "Iffah Mohamad",
    instructorSlug: "iffah",
    instructorImg: "/images/instructors/iffah.jpg",
    thumbnail: "/images/courses/data-science.jpg",
    category: "data-science",
    categoryLabel: "Data Science",
    link: "/courses/data-science-machine-learning",
    duration: "4 months",
    type: "Full-Time",
  },
  {
    id: 4,
    slug: "cloud-architecture-aws-azure",
    title: "Cloud Architecture (AWS & Azure)",
    shortTitle: "Cloud Architecture",
    description:
      "Design and deploy scalable cloud infrastructure. Covers AWS, Azure, serverless, containers, and enterprise cloud cost optimisation.",
    instructor: "Ayesha Nizamdeen",
    instructorSlug: "ayesha",
    instructorImg: "/images/instructors/ayesha.png",
    thumbnail: "/images/courses/cloud-architecture.jpg",
    category: "cloud",
    categoryLabel: "Cloud & DevOps",
    link: "/courses/cloud-architecture-aws-azure",
    duration: "3 months",
    type: "Part-Time",
  },
  {
    id: 5,
    slug: "devops-cicd-pipeline",
    title: "DevOps & CI/CD Pipeline Engineering",
    shortTitle: "DevOps & CI/CD",
    description:
      "Docker, Kubernetes, Jenkins, GitHub Actions & automated deployment pipelines. The DevOps workflow that top engineering teams use.",
    instructor: "Sylvia Moral",
    instructorSlug: "sylvia",
    instructorImg: "/images/instructors/sylvia.jpg",
    thumbnail: "/images/courses/devops.jpg",
    category: "cloud",
    categoryLabel: "Cloud & DevOps",
    link: "/courses/devops-cicd-pipeline",
    duration: "3 months",
    type: "Part-Time",
  },
  {
    id: 6,
    slug: "cybersecurity-fundamentals",
    title: "Cybersecurity Fundamentals",
    shortTitle: "Cybersecurity",
    description:
      "Network security, ethical hacking, vulnerability assessment, OWASP Top 10, compliance frameworks & security architecture.",
    instructor: "Ahmed Muhsin",
    instructorSlug: "ahmed",
    instructorImg: "/images/instructors/ahmed.jpg",
    thumbnail: "/images/courses/cybersecurity.jpg",
    category: "security",
    categoryLabel: "Cybersecurity",
    link: "/courses/cybersecurity-fundamentals",
    duration: "3 months",
    type: "Part-Time",
  },
  {
    id: 7,
    slug: "mobile-app-development",
    title: "Mobile App Development",
    shortTitle: "Mobile Development",
    description:
      "Build cross-platform mobile apps with React Native & Flutter. From design to deployment on iOS and Android app stores.",
    instructor: "Ruwaidha Hakeem",
    instructorSlug: "ruwaidha",
    instructorImg: "/images/instructors/ruwaidha.jpg",
    thumbnail: "/images/courses/mobile-dev.jpg",
    category: "software-engineering",
    categoryLabel: "Software Engineering",
    link: "/courses/mobile-app-development",
    duration: "4 months",
    type: "Part-Time",
  },
  {
    id: 8,
    slug: "database-engineering",
    title: "Database Engineering",
    shortTitle: "Database Engineering",
    description:
      "PostgreSQL, MongoDB, Redis & Elasticsearch. Learn database design, query optimisation, replication & enterprise data architecture.",
    instructor: "Sylvia Moral",
    instructorSlug: "sylvia",
    instructorImg: "/images/instructors/sylvia.jpg",
    thumbnail: "/images/courses/database-engineering.jpg",
    category: "software-engineering",
    categoryLabel: "Software Engineering",
    link: "/courses/database-engineering",
    duration: "2 months",
    type: "Part-Time",
  },
  {
    id: 9,
    slug: "it-project-management-agile",
    title: "IT Project Management & Agile",
    shortTitle: "Agile & Project Mgmt",
    description:
      "Scrum, Kanban, JIRA, stakeholder management & agile delivery. Lead IT projects the way the industry's best teams do it.",
    instructor: "Wasim Imtiasz",
    instructorSlug: "wasim",
    instructorImg: "/images/instructors/wasim.jpg",
    thumbnail: "/images/courses/project-management.jpg",
    category: "management",
    categoryLabel: "IT Management",
    link: "/courses/it-project-management-agile",
    duration: "2 months",
    type: "Part-Time",
  },
];

export const programmes = [
  {
    id: 1,
    slug: "enterprise-developer-track",
    title: "Enterprise Developer Track",
    icon: "fa-code",
    duration: "6 Months",
    type: "Full-Time",
    description:
      "Our flagship program. Go from foundations to building production-grade enterprise systems. Covers full-stack development, databases, cloud deployment & agile practices.",
    highlights: [
      "React + Node.js + PostgreSQL",
      "Cloud deployment (AWS/GCP)",
      "Real enterprise project deliverables",
      "Career placement support",
    ],
    link: "/programmes/enterprise-developer-track",
  },
  {
    id: 2,
    slug: "data-science-bootcamp",
    title: "Data Science Bootcamp",
    icon: "fa-brain",
    duration: "4 Months",
    type: "Full-Time",
    description:
      "Intensive program covering Python, statistical analysis, machine learning, deep learning and model deployment at scale for real business problems.",
    highlights: [
      "Python, Pandas, Scikit-Learn",
      "Machine learning & AI models",
      "Capstone industry project",
      "Data engineering pipelines",
    ],
    link: "/programmes/data-science-bootcamp",
  },
  {
    id: 3,
    slug: "cloud-devops-track",
    title: "Cloud & DevOps Engineer Track",
    icon: "fa-cloud",
    duration: "3 Months",
    type: "Full-Time",
    description:
      "Master cloud infrastructure and DevOps engineering. Hands-on labs with AWS, Docker, Kubernetes and CI/CD pipeline automation.",
    highlights: [
      "AWS Solutions Architect concepts",
      "Docker & Kubernetes",
      "CI/CD with GitHub Actions",
      "Infrastructure as Code (Terraform)",
    ],
    link: "/programmes/cloud-devops-track",
  },
  {
    id: 4,
    slug: "part-time-software-developer",
    title: "Part-Time Software Developer Program",
    icon: "fa-laptop-code",
    duration: "12 Months",
    type: "Part-Time",
    description:
      "Designed for working professionals. Study evenings and weekends and graduate with the skills to transition into a software engineering career.",
    highlights: [
      "Flexible weekend schedule",
      "Same curriculum as full-time track",
      "1-on-1 mentoring sessions",
      "Portfolio project guidance",
    ],
    link: "/programmes/part-time-software-developer",
  },
  {
    id: 5,
    slug: "cybersecurity-professional",
    title: "Cybersecurity Professional Track",
    icon: "fa-shield-halved",
    duration: "3 Months",
    type: "Full-Time",
    description:
      "Comprehensive training in offensive and defensive security. Ethical hacking, penetration testing, security architecture & compliance.",
    highlights: [
      "Ethical hacking & pen testing",
      "Security architecture design",
      "OWASP Top 10 in-depth",
      "Compliance & governance",
    ],
    link: "/programmes/cybersecurity-professional",
  },
  {
    id: 6,
    slug: "mobile-development-bootcamp",
    title: "Mobile Development Bootcamp",
    icon: "fa-mobile-screen",
    duration: "4 Months",
    type: "Full-Time",
    description:
      "Build professional mobile apps with React Native and Flutter. Ship to both iOS and Android from a single codebase with enterprise-quality UI.",
    highlights: [
      "React Native & Flutter",
      "Native device APIs",
      "App Store deployment",
      "Performance optimisation",
    ],
    link: "/programmes/mobile-development-bootcamp",
  },
];

export const instructors = [
  {
    slug: "wasim",
    name: "Wasim Imtiasz",
    img: "/images/instructors/ceo-leader.jpg",
    qualifications: "BA (Hons) Business Mgt (First Class), PGD in Business Administration, CIMA Passed Finalist, ACCA Finalist",
    subject: "IT Project Management & Business Analysis",
    role: "Director / Senior Instructor",
  },
  {
    slug: "rikzy",
    name: "Rikzy Eesa",
    img: "/images/instructors/cmo-leader.jpg",
    qualifications: "ACCA, BSc in Applied Accounting UK",
    subject: "FinTech & IT Finance",
    role: "Lecturer / Director",
  },
  {
    slug: "rimas",
    name: "Rimas Eesa",
    img: "/images/instructors/cto-leader.jpg",
    qualifications: "ACCA Affiliate",
    subject: "FinTech & Business Technology",
    role: "Lecturer / Director",
  },
  {
    slug: "farlan",
    name: "Farlan Hussain",
    img: "/images/instructors/ceo-leader.jpg",
    qualifications: "BSc (Hons) Civil Engineering",
    subject: "Systems Analysis & Computational Thinking",
    role: "Lecturer / Director",
  },
  {
    slug: "sameer",
    name: "Sameer Anis",
    img: "/images/instructors/cto-leader.jpg",
    qualifications: "CIMA, PGD in Business Administration (UoWL)",
    subject: "IT Strategy & Digital Transformation",
    role: "Lecturer / Director",
  },
  {
    slug: "jonathan",
    name: "Jonathan Shehan",
    img: "/images/instructors/jonathan.jpg",
    qualifications: "PGD in Analytical Chemistry, BSc in Chemistry",
    subject: "Data Engineering & Analytics",
    role: "Lecturer",
  },
  {
    slug: "sandamali",
    name: "Sandamali Ekanayake",
    img: "/images/instructors/sandamali.jpg",
    qualifications: "BSc (Hons) in Computing and Information Systems",
    subject: "Computer Science & Software Engineering",
    role: "Lecturer",
  },
  {
    slug: "michelle",
    name: "Michelle Thomasz",
    img: "/images/instructors/michelle.jpg",
    qualifications: "BA in Education (USA), Graduate English Teacher",
    subject: "Technical Communication & Documentation",
    role: "Lecturer",
  },
  {
    slug: "shakeel",
    name: "Dr. Shakeel Jaleel",
    img: "/images/instructors/shakeel.jpg",
    qualifications: "Bachelor of Medicine and Surgery (MBBS)",
    subject: "Bioinformatics & Health Technology",
    role: "Lecturer",
  },
  {
    slug: "thushana",
    name: "Thushana Sathasivam",
    img: "/images/instructors/thushana.jpg",
    qualifications: "BSc (Hons) Psychology, Dip. H.E. Psych. & Couns.",
    subject: "UX Psychology & Human-Computer Interaction",
    role: "Lecturer",
  },
  {
    slug: "harshaka",
    name: "Harshaka Gunarathne",
    img: "/images/instructors/harshaka.jpg",
    qualifications: "BSc Grad. Chem.",
    subject: "Algorithms, Data Structures & Systems",
    role: "Lecturer",
  },
  {
    slug: "desmond",
    name: "Desmond Anthony",
    img: "/images/instructors/desmond.jpg",
    qualifications: "BSc (Hons) Civil Engineering, AMIESL",
    subject: "Systems Engineering & IoT",
    role: "Lecturer",
  },
  {
    slug: "zikra",
    name: "Zikra Jawfer",
    img: "/images/instructors/zikra.jpg",
    qualifications: "BA (Hons) English Studies (reading), Dip. in English Lang. & Lit.",
    subject: "Technical Writing & Communication",
    role: "Lecturer",
  },
  {
    slug: "shazmin",
    name: "Shazmin Anver",
    img: "/images/instructors/shazmin.jpg",
    qualifications: "Biomedical Science",
    subject: "Health IT & Bioinformatics",
    role: "Lecturer",
  },
  {
    slug: "salma",
    name: "Salma Shafeek",
    img: "/images/instructors/salma.jpg",
    qualifications: "BSc Medicinal Chemistry",
    subject: "Scientific Computing & Data Analytics",
    role: "Lecturer",
  },
  {
    slug: "senan",
    name: "Senan Alwis",
    img: "/images/instructors/senan.jpg",
    qualifications: "BSc (Hons) Chemistry",
    subject: "Embedded Systems & Hardware Programming",
    role: "Lecturer",
  },
  {
    slug: "shashini",
    name: "Shashini Dayawansha",
    img: "/images/instructors/shashini.jpg",
    qualifications: "BSc Mathematics and Economics",
    subject: "Data Science & Statistical Modelling",
    role: "Lecturer",
  },
  {
    slug: "basith",
    name: "Basith Mukthar",
    img: "/images/instructors/basith.jpg",
    qualifications: "BSc Accounting & Finance (First Class), CISI, CIM (Stage II)",
    subject: "FinTech & Financial Systems",
    role: "Lecturer",
  },
  {
    slug: "roshane",
    name: "Roshane Dave",
    img: "/images/instructors/roshane.jpg",
    qualifications: "ACCA (reading), CIMA",
    subject: "Digital Accounting & ERP Systems",
    role: "Lecturer",
  },
  {
    slug: "ameen",
    name: "Abdurrahman Ameen",
    img: "/images/instructors/ameen.jpg",
    qualifications: "MBA (Reading), BSc (Hons) in IBM, PQSCM (Level 4)",
    subject: "IT Business Management & Strategy",
    role: "Lecturer",
  },
  {
    slug: "sylvia",
    name: "Sylvia Moral",
    img: "/images/instructors/sylvia.jpg",
    qualifications: "Master in Computer Application (MCA), BSc in Computer Science",
    subject: "ICT & DevOps Engineering",
    role: "Lecturer",
  },
  {
    slug: "ammar",
    name: "Dr. Ammar Jawfer",
    img: "/images/instructors/ammar.jpg",
    qualifications: "MBBS (KDU)",
    subject: "Health Informatics & Medical Technology",
    role: "Lecturer",
  },
  {
    slug: "ahmed",
    name: "Ahmed Muhsin",
    img: "/images/instructors/ahmed.jpg",
    qualifications: "FIT & DIT (UCSC)",
    subject: "Full-Stack Development & ICT",
    role: "Senior Lecturer",
  },
  {
    slug: "ruwaidha",
    name: "Ruwaidha Hakeem",
    img: "/images/instructors/ruwaidha.jpg",
    qualifications: "BEng Software Engineering, Train the Trainer (City & Guilds)",
    subject: "Software Engineering & Mobile Development",
    role: "Senior Lecturer",
  },
  {
    slug: "ali",
    name: "Ali Khalid",
    img: "/images/instructors/ali.jpg",
    qualifications: "ACCA (Professional Level), BSc (Hons) in Applied Accounting (reading)",
    subject: "IT Finance & ERP Systems",
    role: "Lecturer",
  },
  {
    slug: "iffah",
    name: "Iffah Mohamad",
    img: "/images/instructors/iffah.jpg",
    qualifications: "BSc Data Science and Business Analytics",
    subject: "Data Science & Business Intelligence",
    role: "Lecturer",
  },
  {
    slug: "sheikha",
    name: "Sheikha Rifaz",
    img: "/images/instructors/sheikha.jpg",
    qualifications: "ACCA (reading)",
    subject: "IT Economics & Digital Markets",
    role: "Lecturer",
  },
  {
    slug: "mashoor",
    name: "Mashoor Mowlana",
    img: "/images/instructors/mashoor.jpg",
    qualifications: "BSc Economics & Finance (reading)",
    subject: "Digital Finance & IT Auditing",
    role: "Lecturer",
  },
  {
    slug: "uvindu",
    name: "Uvindu Fernando",
    img: "/images/instructors/uvindu.jpg",
    qualifications: "BSc Economics & Management (reading)",
    subject: "IT Management & Business Intelligence",
    role: "Lecturer",
  },
  {
    slug: "arshad",
    name: "Dr. Arshad Hassen",
    img: "/images/instructors/arshad.jpg",
    qualifications: "Bachelor of Medicine, Bachelor of Surgery (M.B.B.S)",
    subject: "Health Technology & Medical Informatics",
    role: "Lecturer",
  },
  {
    slug: "tashini",
    name: "Tashini Vithanage",
    img: "/images/instructors/tashini.jpg",
    qualifications: "MSc in Env. Mgt, BSc (Hons) Biotechnology",
    subject: "Environmental Data Science & GIS",
    role: "Lecturer",
  },
  {
    slug: "noorazra",
    name: "Noor Azra",
    img: "/images/instructors/noorazra.jpg",
    qualifications: "BSc (Hons) in Aquatic Resources Technology",
    subject: "Scientific Data Management",
    role: "Lecturer",
  },
  {
    slug: "ravindu",
    name: "Ravindu Kaveesha",
    img: "/images/instructors/ravindu.jpg",
    qualifications: "Graduate in Chemistry",
    subject: "Scientific Programming & Data Analysis",
    role: "Lecturer",
  },
  {
    slug: "shahela",
    name: "Shahela Sabil",
    img: "/images/instructors/shahela.jpg",
    qualifications: "Master of Business Administration, Bachelor of Arts (BA)",
    subject: "Communication Skills for IT Professionals",
    role: "Lecturer",
  },
  {
    slug: "maryam",
    name: "Maryam Sabil",
    img: "/images/instructors/maryam.jpg",
    qualifications: "BA in Early Childhood Education",
    subject: "Digital Literacy & IT Foundations",
    role: "Lecturer",
  },
  {
    slug: "ayesha",
    name: "Ayesha Nizamdeen",
    img: "/images/instructors/ayesha.png",
    qualifications: "BSc (Hons) Artificial Intelligence (Reading)",
    subject: "Artificial Intelligence & Cloud Architecture",
    role: "Lecturer",
  },
  {
    slug: "sumaiya",
    name: "Sumaiya Rizmal",
    img: "/images/instructors/sumaiya.jpg",
    qualifications: "FND in ICT",
    subject: "ICT & Mathematics for Computing",
    role: "Lecturer",
  },
];

export const testimonials = [
  {
    name: "Natalie Yaseen",
    role: "Software Developer",
    text: "The instructors at Vellix never failed to connect theory with what's actually happening in the industry. It gave us the knowledge and ability to build real systems which made us well-rounded developers.",
  },
  {
    name: "Abdullah Cader",
    role: "Junior Developer",
    text: "Perfect place to learn enterprise software development. Instructors are friendly and effective, making complex topics easy to understand. Simply the best IT academy in Sri Lanka.",
  },
  {
    name: "Rasheef Rashad",
    role: "Full-Stack Developer",
    text: "The lectures are nothing short of amazing. They don't just teach—they create a personal bond with every student and push us to do our best work.",
  },
  {
    name: "Osama Hashim",
    role: "Cloud Engineer",
    text: "With an amazing set of industry-expert instructors, no doubt the best in the business! Landed my first cloud engineering role within 2 months of graduating.",
  },
  {
    name: "Shahid Raza",
    role: "DevOps Engineer",
    text: "Perfect place to get real enterprise skills. The hands-on project work sets Vellix Academy apart from other IT training providers in the country.",
  },
  {
    name: "Himath Paranamana",
    role: "Data Scientist",
    text: "Best panel of lecturers for technology education. The data science program gave me a solid foundation that I use every day in my role. Totally recommended.",
  },
  {
    name: "Zulaika Murad",
    role: "Software Engineer",
    text: "When I first joined I was below average in programming, but with the guidance of the instructors I was finally able to understand the logic behind every system. They were available 24/7 to clear my doubts.",
  },
  {
    name: "Shilvia Thavayogarajah",
    role: "Backend Developer",
    text: "The instructors here have made learning software engineering genuinely fun. I am positive I will never meet another group of mentors as dedicated and passionate.",
  },
  {
    name: "Shakya Wanniarachchi",
    role: "IT Project Manager",
    text: "The exam-oriented and project-driven teaching method makes us feel ready and confident. The classes are very interesting and the environment makes you want to come back every day.",
  },
  {
    name: "Keshani Attanayake",
    role: "Mobile Developer",
    text: "The instructors are amazingly dedicated and passionate, which makes it easier for us to grasp complex concepts. They make sure we understand every detail, no matter how long it takes.",
  },
  {
    name: "Naveed Fazal",
    role: "Cybersecurity Analyst",
    text: "The courses here exceeded my expectations in many regards, especially in the depth of information supplied and how applicable it was to real-world enterprise scenarios.",
  },
  {
    name: "Shavindi Bandaranayake",
    role: "Data Analyst",
    text: "The teaching style is extremely interesting and the depth of understanding the instructors bring to every topic is fascinating. Vellix Academy is where careers get built.",
  },
];

export const newsArticles = [
  {
    id: 1,
    slug: "enterprise-graduates-land-industry-roles",
    title: "Our First Enterprise Developer Track Graduates Land Top Industry Roles",
    date: "March 13, 2024",
    excerpt: "Congratulations to all our graduates who have successfully secured positions at leading tech companies across Sri Lanka and beyond…",
    img: "/images/news/news-1.jpg",
    link: "/news/enterprise-graduates-land-industry-roles",
  },
  {
    id: 2,
    slug: "vellix-expands-with-new-campus",
    title: "Vellix Academy Expands with New State-of-the-Art Campus",
    date: "March 9, 2024",
    excerpt: "Our brand-new campus is now open, equipped with modern labs, dedicated project rooms and high-speed infrastructure for the next generation of IT professionals…",
    img: "/images/news/news-2.jpg",
    link: "/news/vellix-expands-with-new-campus",
  },
  {
    id: 3,
    slug: "it-programs-what-we-teach",
    title: "The IT Programs We Offer: What We Teach and Why It Works",
    date: "March 8, 2024",
    excerpt: "Here at Vellix Academy we offer a wide variety of enterprise IT programs covering full-stack development, data science, cloud computing and cybersecurity…",
    img: "/images/news/news-3.jpg",
    link: "/news/it-programs-what-we-teach",
  },
];

export const galleryImages = [
  { src: "/images/gallery/grad10.jpg", alt: "Graduation Ceremony" },
  { src: "/images/gallery/grad11.jpg", alt: "Award Winners" },
  { src: "/images/gallery/grad12.jpg", alt: "Graduation Highlights" },
  { src: "/images/gallery/grad13.jpg", alt: "Top Performers" },
  { src: "/images/gallery/grad14.jpg", alt: "Graduation Event" },
  { src: "/images/gallery/grad15.jpg", alt: "Campus Event" },
  { src: "/images/gallery/grad16.jpg", alt: "Class of 2024" },
  { src: "/images/gallery/grad17.jpg", alt: "IT Workshop" },
  { src: "/images/gallery/grad18.jpg", alt: "Hackathon Day" },
];

export const stats = [
  { number: 37, label: "Expert Instructors", suffix: "+" },
  { number: 8, label: "Enterprise IT Programs", suffix: "" },
  { number: 500, label: "Graduates Employed", suffix: "+" },
  { number: 50, label: "Partner Companies", suffix: "+" },
];

export const heroSlides = [
  {
    img: "/images/slider/slide-1.jpg",
    title: "Vellix Academy\nEnterprise IT Education",
    subtitle:
      "We teach software development, data science, and cloud computing the way it's actually done at the enterprise level.",
    btnText: "Explore Programs",
    btnLink: "/programmes",
  },
  {
    img: "/images/slider/slide-2.jpg",
    title: "Full-Stack Development\nData Science & Cloud",
    subtitle:
      "Industry-ready programs built around real enterprise projects. Graduate with skills that top companies actually hire for.",
    btnText: "View All Courses",
    btnLink: "/courses",
  },
  {
    img: "/images/slider/slide-3.jpg",
    title: "Learn How Enterprise\nSoftware Gets Built",
    subtitle:
      "Hands-on, project-driven learning with expert instructors who've done it in the industry. No fluff, no theory-only teaching.",
    btnText: "Start a Course",
    btnLink: "/contact",
  },
  {
    img: "/images/slider/slide-4.png",
    title: "Online & In-Person\nFlexible Learning",
    subtitle:
      "Study at our campus or join virtual sessions from anywhere in the world. Same high-quality instruction, your schedule.",
    btnText: "Register Now",
    btnLink: "/register",
  },
  {
    img: "/images/slider/slide-5.jpg",
    title: "Career Placement\nFor Top Performers",
    subtitle:
      "Outstanding graduates get direct introductions to our network of tech companies and startups. We invest in your career.",
    btnText: "Learn More",
    btnLink: "/about",
  },
];

export const faqs = [
  {
    q: "What makes Vellix Academy different from other IT training providers?",
    a: "We focus exclusively on enterprise-grade, production-ready skills. Every programme is built around how software is actually built and deployed in large companies. Our instructors are industry practitioners, not just academics.",
  },
  {
    q: "Do I need prior programming experience to enroll?",
    a: "No. Our Enterprise Developer Track and Data Science Bootcamp both begin with foundational modules designed for beginners. However, some advanced courses (e.g., Cloud Architecture, DevOps) assume basic programming knowledge.",
  },
  {
    q: "Are there virtual/online class options?",
    a: "Yes. All programmes are available in both physical (campus) and virtual (online live sessions) modes. Recordings are provided for every session so you never fall behind.",
  },
  {
    q: "What is the class size?",
    a: "We keep cohorts small (maximum 25 students per batch) to ensure individual attention and a high-quality learning experience.",
  },
  {
    q: "Is there career placement support?",
    a: "Yes. Top performers in each cohort receive direct introductions to our partner companies. We also host regular networking events, tech talks, and mock interview sessions for all students.",
  },
  {
    q: "How do I apply and what are the fees?",
    a: "Fill in the registration form on our website or visit either of our campuses. Our admissions team will contact you within 24 hours to discuss programme fit and fee structure.",
  },
  {
    q: "Do you offer instalment payment plans?",
    a: "Yes. We offer flexible payment plans for all full-time programmes. Contact our admissions office for the latest fee schedules and instalment options.",
  },
  {
    q: "Are there certificates awarded on completion?",
    a: "Yes. All graduates receive a Vellix Academy certificate of completion. For select programmes, preparation for internationally recognised certifications (AWS, Azure, CompTIA) is included.",
  },
];

export const events = [
  {
    id: 1,
    title: "Enterprise Developer Cohort Kickoff – Batch 5",
    date: "2026-07-01",
    month: "JUL",
    day: "01",
    year: "2026",
    location: "Main Campus, Kohuwala",
    description:
      "New batch of the Enterprise Developer Track begins. Orientation, team formation and project briefing sessions for all new students.",
    category: "Programme Launch",
  },
  {
    id: 2,
    title: "Industry Tech Talk: Building Scalable Microservices",
    date: "2026-07-12",
    month: "JUL",
    day: "12",
    year: "2026",
    location: "Online (Zoom)",
    description:
      "A live tech talk with a senior engineer from a Fortune 500 company on building and operating microservices in production.",
    category: "Tech Talk",
  },
  {
    id: 3,
    title: "24-Hour Hackathon – AI for Social Good",
    date: "2026-07-25",
    month: "JUL",
    day: "25",
    year: "2026",
    location: "Main Campus, Kohuwala",
    description:
      "An intensive 24-hour hackathon where teams build AI-powered solutions to real social challenges. Cash prizes and internship opportunities for winners.",
    category: "Hackathon",
  },
  {
    id: 4,
    title: "Data Science Bootcamp – Open Day",
    date: "2026-08-05",
    month: "AUG",
    day: "05",
    year: "2026",
    location: "Main Campus & Online",
    description:
      "Prospective students can attend a free open day to learn about the Data Science Bootcamp curriculum, meet instructors and ask questions.",
    category: "Open Day",
  },
];

export const careers = [
  {
    id: 1,
    title: "Senior Software Instructor – Full-Stack",
    type: "Full-Time",
    location: "Kohuwala, Colombo",
    description:
      "We are looking for an experienced full-stack developer (3+ years) to join our instructor team for the Enterprise Developer Track.",
  },
  {
    id: 2,
    title: "Data Science Instructor",
    type: "Part-Time",
    location: "Hybrid (On-Campus + Online)",
    description:
      "Looking for a practising data scientist or ML engineer to deliver weekend sessions for our Data Science Bootcamp.",
  },
  {
    id: 3,
    title: "Admissions & Student Success Officer",
    type: "Full-Time",
    location: "Kohuwala, Colombo",
    description:
      "Help prospective students find the right programme, manage the admissions process and support students throughout their journey.",
  },
  {
    id: 4,
    title: "Marketing & Content Lead",
    type: "Full-Time",
    location: "Hybrid",
    description:
      "Drive awareness and enrolment through digital marketing, social media content, SEO and partnerships.",
  },
];
