// ============================================================
// Vellix Academy – Content Data
// ============================================================

export const courses = [
  {
    id: 1,
    slug: "foundation-in-information-technology",
    title: "Foundation in Information Technology (FIT)",
    shortTitle: "FIT Program",
    description:
      "The Foundation in Information Technology (FIT) program is designed for students who are new to technology and want to understand how the modern IT industry works before choosing a specialization.",
    duration: "1 Month",
    schedule: "Saturdays Only",
    level: "Beginner",
    lecturers: ["Shahmee Jhan", "Rakesh Nandakumar", "Piusha Pasan"],
    topics: [
      "Digital Foundations",
      "Internet & Networking Basics",
      "Business Systems",
      "Software Development Fundamentals",
      "Cybersecurity Fundamentals",
      "AI & Automation Introduction",
      "Industry Readiness & Career Discovery",
    ],
    perfectFor: [
      "School Leavers",
      "University Beginners",
      "Career Changers",
      "Business Owners",
      "Anyone New to IT",
    ],
    outcome: "Students gain a strong understanding of technology and can confidently choose a professional specialization pathway.",
    thumbnail: "/images/courses/fit.jpg",
    category: "foundation",
    categoryLabel: "Foundation",
    link: "/programmes/foundation-in-information-technology",
  },
  {
    id: 2,
    slug: "business-it-digital-transformation",
    title: "Business IT & Digital Transformation Professional Program",
    shortTitle: "Business IT",
    description:
      "Learn how businesses use technology to solve problems, improve operations, automate processes, and drive growth.",
    duration: "3 Months",
    schedule: "Sundays Only",
    level: "Beginner to Intermediate",
    lecturers: ["Shahmee Jhan"],
    topics: [
      "Business Analysis",
      "Digital Transformation",
      "Process Mapping",
      "Requirements Gathering",
      "Business Systems (POS, CRM, ERP)",
      "Data & Dashboard Thinking",
      "AI & Business Automation",
      "Agile Project Delivery",
      "Professional Communication",
    ],
    perfectFor: [
      "Future Business Analysts",
      "Project Coordinators",
      "IT Consultants",
      "Entrepreneurs",
      "Business Professionals",
    ],
    finalProject: "Develop a complete digital transformation proposal for a real business scenario.",
    thumbnail: "/images/courses/business-it.jpg",
    category: "business-it",
    categoryLabel: "Business IT",
    link: "/programmes/business-it-digital-transformation",
  },
  {
    id: 3,
    slug: "full-stack-development-software-delivery",
    title: "Full-Stack Development & Software Delivery Program",
    shortTitle: "Full-Stack Development",
    description:
      "Build real-world software applications using modern development practices from frontend design to backend systems and deployment.",
    duration: "3 Months",
    schedule: "Sundays Only",
    level: "Beginner to Intermediate",
    lecturers: ["Rakesh Nandakumar"],
    topics: [
      "HTML, CSS & JavaScript",
      "React Development",
      "Laravel Backend Development",
      "REST APIs",
      "Database Design",
      "Authentication & Authorization",
      "Git & GitHub Workflow",
      "Deployment & Hosting",
      "Software Project Delivery",
    ],
    perfectFor: [
      "Future Software Engineers",
      "Web Developers",
      "Application Developers",
      "Technology Enthusiasts",
    ],
    finalProject: "Build and deploy a complete business application with frontend, backend, database, authentication, and documentation.",
    thumbnail: "/images/courses/full-stack.jpg",
    category: "software-development",
    categoryLabel: "Software Development",
    link: "/programmes/full-stack-development-software-delivery",
  },
  {
    id: 4,
    slug: "cybersecurity-fundamentals-defensive-security",
    title: "Cybersecurity Fundamentals & Defensive Security Program",
    shortTitle: "Cybersecurity",
    description:
      "Develop practical cybersecurity knowledge and learn how organizations protect systems, users, and business data.",
    duration: "3 Months",
    schedule: "Sundays Only",
    level: "Beginner to Intermediate",
    lecturers: ["Piusha Pasan"],
    topics: [
      "Cybersecurity Fundamentals",
      "Networking for Security",
      "Linux Basics",
      "Threats & Social Engineering",
      "Password Security & MFA",
      "Web Security Fundamentals",
      "OWASP Top 10",
      "Security Tools & Labs",
      "Incident Response",
      "Business Cybersecurity Controls",
    ],
    perfectFor: [
      "Future Security Analysts",
      "IT Support Professionals",
      "Network Administrators",
      "Security Enthusiasts",
    ],
    finalProject: "Conduct a cybersecurity assessment and present recommendations for a business environment.",
    thumbnail: "/images/courses/cybersecurity.jpg",
    category: "cybersecurity",
    categoryLabel: "Cybersecurity",
    link: "/programmes/cybersecurity-fundamentals-defensive-security",
  },
];

export const programmes = [
  {
    id: 1,
    slug: "enterprise-developer-track",
    title: "Enterprise Developer Track",
    icon: "fa-code",
    duration: "6 Months",
    type: "Full-Time",
    description:
      "Our flagship program. Go from foundations to building production-grade enterprise systems. Covers full-stack development, databases, cloud deployment & agile practices.",
    highlights: [
      "React + Node.js + PostgreSQL",
      "Cloud deployment (AWS/GCP)",
      "Real enterprise project deliverables",
      "Career placement support",
    ],
    link: "/programmes/enterprise-developer-track",
  },
  {
    id: 2,
    slug: "data-science-bootcamp",
    title: "Data Science Bootcamp",
    icon: "fa-brain",
    duration: "4 Months",
    type: "Full-Time",
    description:
      "Intensive program covering Python, statistical analysis, machine learning, deep learning and model deployment at scale for real business problems.",
    highlights: [
      "Python, Pandas, Scikit-Learn",
      "Machine learning & AI models",
      "Capstone industry project",
      "Data engineering pipelines",
    ],
    link: "/programmes/data-science-bootcamp",
  },
  {
    id: 3,
    slug: "cloud-devops-track",
    title: "Cloud & DevOps Engineer Track",
    icon: "fa-cloud",
    duration: "3 Months",
    type: "Full-Time",
    description:
      "Master cloud infrastructure and DevOps engineering. Hands-on labs with AWS, Docker, Kubernetes and CI/CD pipeline automation.",
    highlights: [
      "AWS Solutions Architect concepts",
      "Docker & Kubernetes",
      "CI/CD with GitHub Actions",
      "Infrastructure as Code (Terraform)",
    ],
    link: "/programmes/cloud-devops-track",
  },
  {
    id: 4,
    slug: "part-time-software-developer",
    title: "Part-Time Software Developer Program",
    icon: "fa-laptop-code",
    duration: "12 Months",
    type: "Part-Time",
    description:
      "Designed for working professionals. Study evenings and weekends and graduate with the skills to transition into a software engineering career.",
    highlights: [
      "Flexible weekend schedule",
      "Same curriculum as full-time track",
      "1-on-1 mentoring sessions",
      "Portfolio project guidance",
    ],
    link: "/programmes/part-time-software-developer",
  },
  {
    id: 5,
    slug: "cybersecurity-professional",
    title: "Cybersecurity Professional Track",
    icon: "fa-shield-halved",
    duration: "3 Months",
    type: "Full-Time",
    description:
      "Comprehensive training in offensive and defensive security. Ethical hacking, penetration testing, security architecture & compliance.",
    highlights: [
      "Ethical hacking & pen testing",
      "Security architecture design",
      "OWASP Top 10 in-depth",
      "Compliance & governance",
    ],
    link: "/programmes/cybersecurity-professional",
  },
  {
    id: 6,
    slug: "mobile-development-bootcamp",
    title: "Mobile Development Bootcamp",
    icon: "fa-mobile-screen",
    duration: "4 Months",
    type: "Full-Time",
    description:
      "Build professional mobile apps with React Native and Flutter. Ship to both iOS and Android from a single codebase with enterprise-quality UI.",
    highlights: [
      "React Native & Flutter",
      "Native device APIs",
      "App Store deployment",
      "Performance optimisation",
    ],
    link: "/programmes/mobile-development-bootcamp",
  },
];

export const instructors = [
  {
    slug: "shahmee-jhan",
    name: "Shahmee Jhan",
    img: "/images/instructors/shahmee-jhan.jpg",
    qualifications: "BSc (Hons) Computer Science",
    subject: "Foundation (FIT), Business IT & Digital Transformation",
    role: "Senior Instructor",
  },
  {
    slug: "rakesh-nandakumar",
    name: "Rakesh Nandakumar",
    img: "/images/instructors/rakesh-nandakumar.jpg",
    qualifications: "BSc (Hons) Computer Science",
    subject: "Foundation (FIT), Full-Stack Development & Software Delivery Program",
    role: "Senior Instructor",
  },
  {
    slug: "piusha-pasan",
    name: "Piusha Pasan",
    img: "/images/instructors/piusha-pasan.jpg",
    qualifications: "BSc (Hons) Cyber Security",
    subject: "Foundation (FIT), Cybersecurity Fundamentals & Defensive Security Program",
    role: "Senior Instructor",
  },
];

export const testimonials = [
  {
    name: "Natalie Yaseen",
    role: "Software Developer",
    text: "The instructors at Vellix never failed to connect theory with what's actually happening in the industry. It gave us the knowledge and ability to build real systems which made us well-rounded developers.",
  },
  {
    name: "Abdullah Cader",
    role: "Junior Developer",
    text: "Perfect place to learn enterprise software development. Instructors are friendly and effective, making complex topics easy to understand. Simply the best IT academy in Sri Lanka.",
  },
  {
    name: "Rasheef Rashad",
    role: "Full-Stack Developer",
    text: "The lectures are nothing short of amazing. They don't just teach—they create a personal bond with every student and push us to do our best work.",
  },
  {
    name: "Osama Hashim",
    role: "Cloud Engineer",
    text: "With an amazing set of industry-expert instructors, no doubt the best in the business! Landed my first cloud engineering role within 2 months of graduating.",
  },
  {
    name: "Shahid Raza",
    role: "DevOps Engineer",
    text: "Perfect place to get real enterprise skills. The hands-on project work sets Vellix Academy apart from other IT training providers in the country.",
  },
  {
    name: "Himath Paranamana",
    role: "Data Scientist",
    text: "Best panel of lecturers for technology education. The data science program gave me a solid foundation that I use every day in my role. Totally recommended.",
  },
  {
    name: "Zulaika Murad",
    role: "Software Engineer",
    text: "When I first joined I was below average in programming, but with the guidance of the instructors I was finally able to understand the logic behind every system. They were available 24/7 to clear my doubts.",
  },
  {
    name: "Shilvia Thavayogarajah",
    role: "Backend Developer",
    text: "The instructors here have made learning software engineering genuinely fun. I am positive I will never meet another group of mentors as dedicated and passionate.",
  },
  {
    name: "Shakya Wanniarachchi",
    role: "IT Project Manager",
    text: "The exam-oriented and project-driven teaching method makes us feel ready and confident. The classes are very interesting and the environment makes you want to come back every day.",
  },
  {
    name: "Keshani Attanayake",
    role: "Mobile Developer",
    text: "The instructors are amazingly dedicated and passionate, which makes it easier for us to grasp complex concepts. They make sure we understand every detail, no matter how long it takes.",
  },
  {
    name: "Naveed Fazal",
    role: "Cybersecurity Analyst",
    text: "The courses here exceeded my expectations in many regards, especially in the depth of information supplied and how applicable it was to real-world enterprise scenarios.",
  },
  {
    name: "Shavindi Bandaranayake",
    role: "Data Analyst",
    text: "The teaching style is extremely interesting and the depth of understanding the instructors bring to every topic is fascinating. Vellix Academy is where careers get built.",
  },
];

export const newsArticles = [
  {
    id: 1,
    slug: "foundation-in-information-technology-fit",
    title: "Foundation in Information Technology (FIT): The Perfect Starting Point for Your IT Career",
    date: "August 15, 2026",
    excerpt: "Discover how Vellix Academy's Foundation in Information Technology (FIT) Program helps students build a strong understanding of Business IT, Software Development, Cybersecurity, AI, and Industry Readiness before selecting a specialization.",
    img: "/images/news/news-1.jpg",
    link: "/news/foundation-in-information-technology-fit",
    content: [
      "The technology industry offers endless opportunities, but many students struggle because they don't know where to start.",
      "The Foundation in Information Technology (FIT) Program at Vellix Academy was designed to solve this challenge.",
      "Over five weeks, students gain practical exposure to:",
      "• Business IT & Digital Transformation",
      "• Software Development",
      "• Cybersecurity",
      "• Artificial Intelligence",
      "• Networking Fundamentals",
      "• Industry Readiness",
      "Rather than jumping directly into coding or security, students first understand how technology works as a complete ecosystem.",
      "This foundation enables learners to make informed decisions about their future career pathways and prepares them for professional specialization programs.",
    ],
  },
  {
    id: 2,
    slug: "business-it-hidden-career-path",
    title: "Business IT: The Hidden Career Path Behind Every Successful Technology Project",
    date: "August 18, 2026",
    excerpt: "Most people know about programmers and cybersecurity professionals, but very few understand the role of Business IT specialists.",
    img: "/images/news/news-2.jpg",
    link: "/news/business-it-hidden-career-path",
    content: [
      "Every successful technology solution begins with understanding a business problem.",
      "Business IT professionals act as the bridge between business needs and technical solutions.",
      "They help organizations:",
      "• Improve operations",
      "• Reduce manual work",
      "• Automate processes",
      "• Improve customer experiences",
      "• Support business growth",
      "At Vellix Academy, our Business IT pathway introduces students to:",
      "• Business Analysis",
      "• Digital Transformation",
      "• Process Mapping",
      "• CRM & ERP Systems",
      "• AI & Automation",
      "• Project Coordination",
      "Business IT is one of the fastest-growing fields for professionals who enjoy both technology and business strategy.",
    ],
  },
  {
    id: 3,
    slug: "why-cybersecurity-matters-more-than-ever",
    title: "Why Cybersecurity Matters More Than Ever in Today's Digital World",
    date: "August 22, 2026",
    excerpt: "From phishing attacks to data breaches, cybersecurity has become a critical skill for every organization.",
    img: "/images/news/news-3.jpg",
    link: "/news/why-cybersecurity-matters-more-than-ever",
    content: [
      "Every day, businesses face threats from cybercriminals attempting to steal information, disrupt services, or gain unauthorized access.",
      "Cybersecurity is no longer a concern only for large corporations.",
      "Small businesses, startups, educational institutions, and individuals all need strong security practices.",
      "Students in Vellix Academy's Cybersecurity pathway learn:",
      "• Security Fundamentals",
      "• Networking Security",
      "• Threat Awareness",
      "• Digital Safety",
      "• Security Best Practices",
      "• Risk Management",
      "The goal is not only to understand attacks but also to learn how to protect people, systems, and businesses responsibly.",
    ],
  },
  {
    id: 4,
    slug: "from-idea-to-application-full-stack-development",
    title: "From Idea to Application: Understanding Full-Stack Development",
    date: "August 25, 2026",
    excerpt: "Ever wondered how websites and mobile applications are built? Full-Stack Development provides the answer.",
    img: "/images/news/news-4.jpg",
    link: "/news/from-idea-to-application-full-stack-development",
    content: [
      "Modern software applications consist of multiple layers working together.",
      "A Full-Stack Developer understands:",
      "• User Interfaces (Frontend)",
      "• Business Logic (Backend)",
      "• Databases",
      "• APIs",
      "• Deployment",
      "• System Integration",
      "At Vellix Academy, students learn practical development skills through real-world projects and industry-focused exercises.",
      "By the end of the specialization pathway, students gain experience building applications similar to those used by businesses every day.",
    ],
  },
  {
    id: 5,
    slug: "artificial-intelligence-changing-future-of-work",
    title: "Artificial Intelligence Is Changing the Future of Work",
    date: "August 28, 2026",
    excerpt: "AI is transforming industries worldwide. Learn how modern professionals can work alongside AI rather than compete against it.",
    img: "/images/news/news-5.jpg",
    link: "/news/artificial-intelligence-changing-future-of-work",
    content: [
      "Artificial Intelligence has rapidly become one of the most influential technologies of our generation.",
      "Businesses are using AI to:",
      "• Improve customer support",
      "• Automate repetitive tasks",
      "• Generate reports",
      "• Analyze business data",
      "• Increase productivity",
      "At Vellix Academy, students are introduced to practical AI concepts and responsible AI usage.",
      "Our focus is on helping learners understand how AI can support business growth and innovation rather than simply replacing jobs.",
    ],
  },
  {
    id: 6,
    slug: "choosing-right-technology-career-path",
    title: "Choosing the Right Technology Career Path",
    date: "September 1, 2026",
    excerpt: "Not sure whether to choose Business IT, Software Development, or Cybersecurity? Here's how to decide.",
    img: "/images/news/news-6.jpg",
    link: "/news/choosing-right-technology-career-path",
    content: [
      "Every student has different strengths and interests.",
      "You may enjoy:",
      "Business IT",
      "If you enjoy:",
      "• Problem solving",
      "• Business processes",
      "• Communication",
      "• Strategy",
      "Full-Stack Development",
      "If you enjoy:",
      "• Building applications",
      "• Coding",
      "• Technology creation",
      "• System design",
      "Cybersecurity",
      "If you enjoy:",
      "• Protecting systems",
      "• Investigating threats",
      "• Security awareness",
      "• Risk management",
      "The FIT Foundation Program helps students explore all three areas before choosing the specialization that best aligns with their goals.",
    ],
  },
];

export const galleryImages = [
  { src: "/images/gallery/grad10.jpg", alt: "Graduation Ceremony" },
  { src: "/images/gallery/grad11.jpg", alt: "Award Winners" },
  { src: "/images/gallery/grad12.jpg", alt: "Graduation Highlights" },
  { src: "/images/gallery/grad13.jpg", alt: "Top Performers" },
  { src: "/images/gallery/grad14.jpg", alt: "Graduation Event" },
  { src: "/images/gallery/grad15.jpg", alt: "Campus Event" },
  { src: "/images/gallery/grad16.jpg", alt: "Class of 2024" },
  { src: "/images/gallery/grad17.jpg", alt: "IT Workshop" },
  { src: "/images/gallery/grad18.jpg", alt: "Hackathon Day" },
];

export const stats = [
  { number: 3, label: "Expert Instructors", suffix: "+" },
  { number: 3, label: "Enterprise IT Programs", suffix: "" },
  { number: 200, label: "Graduates Employed", suffix: "+" },
  { number: 10, label: "Partner Companies", suffix: "+" },
];

export const heroSlides = [
  {
    img: "/images/slider/slide-1.jpg",
    title: "Vellix Academy\nEnterprise IT Education",
    subtitle:
      "We teach software development, data science, and cloud computing the way it's actually done at the enterprise level.",
    btnText: "Explore Programs",
    btnLink: "/programmes",
  },
  {
    img: "/images/slider/slide-2.jpg",
    title: "Full-Stack Development\nData Science & Cloud",
    subtitle:
      "Industry-ready programs built around real enterprise projects. Graduate with skills that top companies actually hire for.",
    btnText: "View All Courses",
    btnLink: "/courses",
  },
  {
    img: "/images/slider/slide-3.jpg",
    title: "Learn How Enterprise\nSoftware Gets Built",
    subtitle:
      "Hands-on, project-driven learning with expert instructors who've done it in the industry. No fluff, no theory-only teaching.",
    btnText: "Start a Course",
    btnLink: "/contact",
  },
  {
    img: "/images/slider/slide-4.png",
    title: "Online & In-Person\nFlexible Learning",
    subtitle:
      "Study at our campus or join virtual sessions from anywhere in the world. Same high-quality instruction, your schedule.",
    btnText: "Register Now",
    btnLink: "/register",
  },
  {
    img: "/images/slider/slide-5.jpg",
    title: "Career Placement\nFor Top Performers",
    subtitle:
      "Outstanding graduates get direct introductions to our network of tech companies and startups. We invest in your career.",
    btnText: "Learn More",
    btnLink: "/about",
  },
];

export const faqs = [
  {
    q: "What is Vellix Academy?",
    a: "Vellix Academy is a technology-focused learning academy designed to help students develop practical skills in Business IT, Software Development, Cybersecurity, Artificial Intelligence, and Digital Transformation through industry-oriented learning experiences.",
  },
  {
    q: "What is the Foundation in Information Technology (FIT) Program?",
    a: "The Foundation in Information Technology (FIT) Program is designed for students who are new to technology and want to build a strong understanding of modern IT concepts before choosing a specialization pathway. The program covers Business IT, Software Development, Cybersecurity, Networking, Artificial Intelligence, and Industry Readiness.",
  },
  {
    q: "Is the Foundation Program mandatory?",
    a: "No. The Foundation Program is recommended for beginners and students who are new to Information Technology. Students who already possess basic IT knowledge and meet the entry requirements may enroll directly into their preferred specialization program.",
  },
  {
    q: "What are the specialization programs available?",
    a: "Students can choose from the following professional specialization pathways: Business IT & Digital Transformation, Full-Stack Development & Software Engineering, and Cybersecurity & Networking. Each pathway is designed to provide practical industry-focused knowledge and skills.",
  },
  {
    q: "What are the minimum entry requirements?",
    a: "Applicants should have completed their G.C.E. Ordinary Level (O/L) examination. Basic computer literacy and an interest in technology are recommended.",
  },
  {
    q: "How do I know whether I should start with Foundation or a Specialization Program?",
    a: "If you are completely new to Information Technology, the FIT Foundation Program is recommended. If you already have a basic understanding of IT concepts and know which field you wish to pursue, you may apply directly to a specialization program.",
  },
  {
    q: "Are the classes practical or theoretical?",
    a: "Vellix Academy focuses on practical learning through real-world examples, workshops, case studies, demonstrations, projects, presentations, and industry-based activities. Our goal is to help students develop skills that can be applied in real business and technology environments.",
  },
  {
    q: "Will I work on projects during the program?",
    a: "Yes. Students will participate in practical exercises, industry scenarios, case studies, and project-based activities throughout their learning journey. Specialization programs include more advanced project work aligned with real industry requirements.",
  },
  {
    q: "Do you provide internships or industry exposure opportunities?",
    a: "Selected students who successfully complete their specialization programs may be considered for internship opportunities, workplace exposure, project involvement, or industry placements through Vellix Academy's professional network and associated organizations. Opportunities are based on student performance, availability, and selection criteria.",
  },
  {
    q: "Does Vellix Academy guarantee employment?",
    a: "No educational institution can guarantee employment. However, outstanding students may be recommended for employment opportunities within our professional network, associated organizations, or partner companies when suitable opportunities become available.",
  },
  {
    q: "Will I receive a certificate after completing a program?",
    a: "Yes. Students who successfully complete their program requirements will receive a Vellix Academy Certificate of Completion. Additional recognition may be awarded for exceptional performance and achievements.",
  },
  {
    q: "Why should I choose Vellix Academy?",
    a: "Vellix Academy combines practical learning, industry-focused training, professional specialization pathways, project-based experience, career development guidance, and access to industry exposure opportunities. Our mission is to help students develop real-world skills, professional confidence, and future-ready technology expertise.",
  },
];

export const events = [
  {
    id: 1,
    title: "Foundation in Information Technology (FIT) – Batch 01",
    date: "2026-09-05",
    month: "SEP",
    day: "05",
    year: "2026",
    location: "Vellix Academy",
    description:
      "The official launch of Vellix Academy's 5-Week Foundation Program. Students will explore Business IT, Software Development, Cybersecurity, Artificial Intelligence, Networking, and Industry Readiness through practical learning sessions.",
    category: "PROGRAM INTAKE",
    buttonText: "Register Now",
  },
  {
    id: 2,
    title: "Student Orientation & Program Introduction",
    date: "2026-09-05",
    month: "SEP",
    day: "05",
    year: "2026",
    location: "Vellix Academy",
    description:
      "Meet your lecturers, understand the academy structure, explore career pathways, and prepare for your learning journey.",
    category: "ORIENTATION",
    buttonText: "Register Now",
    lecturers: ["Shahmee Jhan", "Rakesh Nandakumar", "Piusha Pasan"],
  },
  {
    id: 3,
    title: "Week 2 – Internet & Business Systems",
    date: "2026-09-12",
    month: "SEP",
    day: "12",
    year: "2026",
    location: "Vellix Academy",
    description:
      "Learn how websites, applications, networking, POS systems, CRM platforms, and business technologies work together in modern organizations.",
    category: "FOUNDATION PROGRAM",
    buttonText: "Learn More",
  },
  {
    id: 4,
    title: "Week 3 – AI, Automation & Cybersecurity",
    date: "2026-09-19",
    month: "SEP",
    day: "19",
    year: "2026",
    location: "Vellix Academy",
    description:
      "Discover artificial intelligence, automation technologies, cybersecurity fundamentals, digital safety, and emerging technology trends.",
    category: "FOUNDATION PROGRAM",
    buttonText: "Learn More",
  },
  {
    id: 5,
    title: "Week 4 – Industry Readiness & Career Discovery",
    date: "2026-09-26",
    month: "SEP",
    day: "26",
    year: "2026",
    location: "Vellix Academy",
    description:
      "Explore career pathways in Business IT, Software Development, and Cybersecurity while building industry awareness and professional skills.",
    category: "FOUNDATION PROGRAM",
    buttonText: "Learn More",
  },
  {
    id: 6,
    title: "FIT Innovation Challenge & Student Presentations",
    date: "2026-10-03",
    month: "OCT",
    day: "03",
    year: "2026",
    location: "Vellix Academy",
    description:
      "Students present technology solutions for real-world business scenarios and demonstrate their understanding of technology, business, and innovation.",
    category: "FOUNDATION COMPLETION",
    buttonText: "View Event",
  },
  {
    id: 7,
    title: "Choose Your Professional Specialization",
    date: "2026-10-10",
    month: "OCT",
    day: "10",
    year: "2026",
    location: "Vellix Academy",
    description:
      "Students may continue their learning journey by selecting one of the following pathways: Business IT & Digital Transformation, Full-Stack Development & Software Engineering, Cybersecurity & Ethical Security Practices.",
    category: "SPECIALIZATION ENROLLMENT",
    buttonText: "Apply Now",
    pathways: [
      "Business IT & Digital Transformation",
      "Full-Stack Development & Software Engineering",
      "Cybersecurity & Ethical Security Practices",
    ],
  },
  {
    id: 8,
    title: "Professional Specialization Programs – Batch 01",
    date: "2026-10-17",
    month: "OCT",
    day: "17",
    year: "2026",
    location: "Vellix Academy",
    description:
      "The first intake for Vellix Academy's 3-Month Professional Programs begins.",
    category: "PROGRAM LAUNCH",
    buttonText: "Enroll Now",
    tracks: [
      "Business IT & Digital Transformation",
      "Full-Stack Development & Software Engineering",
      "Cybersecurity & Ethical Security Practices",
    ],
  },
];

export const careers = [
  {
    id: 1,
    title: "English Communication & Career Development Trainer",
    type: "Part-Time",
    location: "On-Campus",
    description:
      "Deliver Business English sessions, conduct interview preparation workshops, support career readiness programs, and help students improve communication skills.",
    requirements: [
      "Strong spoken and written English skills",
      "Experience in professional communication training",
      "Knowledge of interview preparation and CV writing",
      "Ability to conduct interactive classroom sessions",
      "Teaching or corporate training experience preferred",
    ],
    responsibilities: [
      "Deliver Business English sessions",
      "Conduct interview preparation workshops",
      "Support career readiness programs",
      "Help students improve communication skills",
    ],
  },
  {
    id: 2,
    title: "Digital Marketing Lecturer",
    type: "Part-Time",
    location: "On-Campus",
    description:
      "Deliver practical marketing sessions, teach digital branding and campaign management, and guide students on marketing tools and platforms.",
    requirements: [
      "Experience in Digital Marketing",
      "Knowledge of Social Media Marketing",
      "SEO and Content Marketing experience",
      "Familiarity with Google Ads and Analytics",
      "Industry experience preferred",
    ],
    responsibilities: [
      "Deliver practical marketing sessions",
      "Teach digital branding and campaign management",
      "Guide students on marketing tools and platforms",
    ],
  },
  {
    id: 3,
    title: "Data Analytics & Business Intelligence Lecturer",
    type: "Part-Time",
    location: "On-Campus",
    description:
      "Deliver Data Analytics training, teach reporting and dashboard development, and conduct practical business analysis exercises.",
    requirements: [
      "Experience with Excel, Power BI, or Tableau",
      "Understanding of business reporting and KPIs",
      "Data analysis experience preferred",
      "Teaching experience is an advantage",
    ],
    responsibilities: [
      "Deliver Data Analytics training",
      "Teach reporting and dashboard development",
      "Conduct practical business analysis exercises",
    ],
  },
  {
    id: 4,
    title: "Artificial Intelligence & Automation Trainer",
    type: "Part-Time",
    location: "On-Campus",
    description:
      "Conduct AI workshops, teach practical AI applications, and introduce automation concepts and tools.",
    requirements: [
      "Experience using AI tools and automation platforms",
      "Knowledge of prompt engineering and AI workflows",
      "Understanding of business AI applications",
      "Industry experience preferred",
    ],
    responsibilities: [
      "Conduct AI workshops",
      "Teach practical AI applications",
      "Introduce automation concepts and tools",
    ],
  },
  {
    id: 5,
    title: "Graphic Design & Creative Media Lecturer",
    type: "Part-Time",
    location: "On-Campus",
    description:
      "Deliver design and creative media training, guide students in branding and content creation, and support project-based learning activities.",
    requirements: [
      "Experience with Adobe Creative Suite, Canva, or Figma",
      "Portfolio of design projects",
      "Understanding of branding and visual communication",
      "Teaching experience preferred",
    ],
    responsibilities: [
      "Deliver design and creative media training",
      "Guide students in branding and content creation",
      "Support project-based learning activities",
    ],
  },
  {
    id: 6,
    title: "Human Resource Management Lecturer",
    type: "Part-Time",
    location: "On-Campus",
    description:
      "Deliver HR-related training programs, conduct practical HR workshops, and support future HRM programme development.",
    requirements: [
      "Degree or professional qualification in HRM",
      "Industry HR experience preferred",
      "Knowledge of recruitment, employee relations, and performance management",
      "Strong communication skills",
    ],
    responsibilities: [
      "Deliver HR-related training programs",
      "Conduct practical HR workshops",
      "Support future HRM programme development",
    ],
  },
  {
    id: 7,
    title: "Student Success & Academic Coordinator",
    type: "Full-Time",
    location: "On-Campus",
    description:
      "Student support and engagement, attendance and academic coordination, communication with students and parents, and academic scheduling and administration.",
    requirements: [
      "Strong administrative and communication skills",
      "Ability to coordinate schedules and student activities",
      "Experience in education administration preferred",
      "Good organizational skills",
    ],
    responsibilities: [
      "Student support and engagement",
      "Attendance and academic coordination",
      "Communication with students and parents",
      "Academic scheduling and administration",
    ],
  },
];
